### ISSUE TITLE
Unusable (hangs X while running) on ubuntu 16.04?

### ISSUE THREAD

**Issue by aiobofh** [rncbc/qjackctl#13] opened 2016-06-17 08:22 UTC
Hi,

Today I was going to create some music - Started up my dedicated DAW machine and I encountered a _very_ strange problem with qjackctl:

When I run it from console Xorg just hangs there, until I press Ctrl-C... I thought it had something to do with my IRQ prioritization on the realtime-stuff, so I logged in from another machine using ssh -X and started qjackctl from there. Then the Xorg issue occurred on THAT machine too... Everything freezes until I killed the qjackctl process. What happened here?

Very anxious for some clarification/workaround. It seems to be a GUI issue?

... I don't get _anything_ in logs. Nor console output. 

Kind regards,
/AiO

**Comment by dragontamer8740** [comment] 2016-10-08 00:38
This just happened to me too. Debian Sid.

**Comment by Rsantct** [comment] 2016-10-16 22:20
The same problem to me. Just installed a new Ubuntu 16.04.
Qjackctl runs on my local desktop, but it not emerges over my ssh -X session as usually does.
Also, if any X app where running over my ssh connection, when trying to run qjackctl it freezes any X app. If I kill the qjackctl process then the others X app resumes to work again...

**Comment by dragontamer8740** [comment] 2016-10-17 00:55
Hm, when I upgraded qjackctl (apt-get update; apt-get install qjackctl) it solved itself somehow.

Still, this is weird.

**Comment by aiobofh** [comment] 2016-10-17 07:23
Hi guys,

It seems that the qjackctl bundled with Ubuntu has some QT issues with some "non-standard" window managers. I tried FVWM and Awesome and the same symptoms occur. It seem to be strictly a QT5 problem as far as I understand it. I see the same problem with Qsampler and other QT-applications.... I ended up using the kxstudio repositories for the qjackctl and other things. They work flawless for me.

Check this out:
http://kxstudio.linuxaudio.org/Repositories

I hope this helps you guys as well! :)

Kind regards,
/AiO

**Comment by Rsantct** [comment] 2016-10-17 10:25
Ok, I've deinstalled the Ubuntu standard package, then downloaded the stable debian package.
$ sudo apt-get remove --purge qjackctl
$ wget http://ftp.de.debian.org/debian/pool/main/q/qjackctl/qjackctl_0.3.12-1_amd64.deb
$  sudo apt install ./qjackctl_0.3.12-1_amd64.deb
Things work again !
:-)

**Comment by rncbc** [comment] 2016-10-18 10:34
can you build to default qt5, from latest git head (qjackctl v0.4.3.7+) and test whether the issue still occurs?

cheers

**Comment by Grissess** [comment] 2017-01-17 06:02
Might as well throw in two cents, since this is rare and I doubt many others will encounter this :)

I can confirm that it happens on my machine; according to `-v`, one gets:

```
Qt: 5.7.1
QjackCtl: 0.4.4  (Jan 15 2017 21:34 -0500)
```

This is a rather fresh [Exherbo](http://exherbo.org/) Linux build, and it has some idiosyncracies--in particular, I have `-systemd -dbus` in the global options (I've been building runit services manually), and the window manager is [i3wm](http://i3wm.org/). I recall encountering this on Gentoo a while ago with the same USE and wm, and forgetting what I did to work around it.

The exact symptoms are as follows:

1. Start qjackctl
2. X "hangs"; all windows (including WM areas) appear to become unresponsive--in fact, it appears they never render. Input events appear to be passed--changing VTs and killing qjackctl "unhangs" X and demonstrates that, e.g., keypresses were acknowledged by my xvt.

I tried strace and ltrace, but to no avail; the former rapidly fills with IPC from X, and the latter gets flooded with far too many calls to Qt :) .

I don't suspect this is qjackctl's fault alone, but I'd gladly help you work around whatever demons it appears to be angering. In particular, I should let you know if I manage a workaround in the system config; in the meantime, I'm open to suggestions.

(Thanks for the software, by the way :)

**Comment by aiobofh** [comment] 2017-01-17 07:39
Workaround (for some distros): Install the KXStudio (http://kxstudio.linuxaudio.org/) maintained version of qjackctl. It seem to work better with later QT's in integration with "non-standard" window managers and such things. Works for me with Ubuntu at least; using these instructions http://kxstudio.linuxaudio.org/Repositories

But I agree. It would be nice with a less cumbersome workaround. Not all of us want to run main stream window managers for various reasons.

**Comment by noobermin** [comment] 2018-06-13 05:49
Message from the future, this still affects 0.4.5. Also using i3wm, and qjackctl and qsyth show cause similar behavior.

And no, I'm installing another operating system to "fix" it.

**Comment by senisioi** [comment] 2018-08-08 11:15
This looks like it's fixed with the latest git checkout on ubuntu 16.04. I compiled it with qt4 ./configure --enable-qt4

**Closed** 2018-10-20 12:00 UTC

**Comment by quaeched** [comment] 2018-11-14 09:46
just noticed that when I run startx, qjackctl runs flawlessly. however after running xinit /usr/bin/openbox-session, X hangs. any ideas on why this could be happening? Thank You

**Comment by rncbc** [comment] 2018-11-14 10:32
@quaeched : no idea but blame openbox ?

you may try with ./configure --disable-xunique ...

**Comment by quaeched** [comment] 2018-11-14 17:15
@rncbc well I thought, since startx also runs openbox, maybe it could be permissions or something like that? see for example, just to be able to run xinit /usrb/bin/openbox-session, i had to put `needs_root_rights=yes` into /etc/X11/Xwrapper.config. what do You think?

**Comment by rncbc** [comment] 2018-11-14 18:17
qjackctl does not need root privileges at all, so i have still no idea.

**Comment by quaeched** [comment] 2018-11-15 14:17
ok, thanks. will keep You updated.

**Comment by ebfe** [comment] 2019-01-09 09:51
This is still an issue in 0.5.5 (and qt5 5.11). The only workaround that works for me is switching to a (non-tiling) window manager.

While qsynth exhibits the same behaviour, pretty much every other qt5 app i tried works just fine.

Are qjackctl/qsynth doing anything unusual with regards to X11 events/resizing?

**Comment by ebfe** [comment] 2019-01-09 09:55
Building with `--disable-xuniqe` seems to fix this.

**Comment by Grissess** [comment] 2019-01-09 11:53
I take it you mean `--disable-xunique`: https://github.com/rncbc/qjackctl/blob/master/configure.ac#L135-L139

...yet another obscure X extension, I guess? Cursory searching seems to reveal that:

- The two main users of this extension are qjackctl and qsynth, which appear so affected;
- disabling this is a [known workaround](http://linux-audio.4202.n7.nabble.com/qjackctl-freezing-desktop-td104541.html) from another thread, which details the actual issue from the X perspective *for this project*; and
- I'm having a hard time finding any documentation for the protocol to start with--searching returns mostly the above results.

Do any of the developers know about these--including why it's an optional dependency that defaults to on? (My local build painfully doesn't have this option parameterized, and I'm going to be busy today, so I'll get a positive report on whether disabling it works later.)

**Comment by ebfe** [comment] 2019-01-09 13:22
> I take it you mean `--disable-xunique`: https://github.com/rncbc/qjackctl/blob/master/configure.ac#L135-L139
Yes, edited the comment.

> ...yet another obscure X extension, I guess? 

As far as I can tell this isn't a X11 extension. The purpose of
CONFIG_XUNIQUE seems to be to limit qjackctl to a single running
instance. If enabled, running a second qjackctl tries to raise
the existing instances window into the foreground and exit. Maybe it's
just the window manager and qjackctl fighting over control of the
window.

**Comment by AlbertVeli** [comment] 2019-02-15 18:28
This is still an issue with the latest git version. Tested today with awesome and:
```
qjackctl -v
Qt: 5.11.3
QjackCtl: 0.5.5.11git.a874c5
```
and the workaround mentioned above works:
```
./configure --disable-xunique
```
